name: HungerGamesLobby
version: '${project.version}'
main: dev.sylus.hungergameslobby.HungerGamesLobby
api-version: '1.18'

commands:
  hologramTest:
    description: spawns a hologram
    usage: /hologramTest
    permission: hungerGamesLobby.admin

  sendPlayer:
    description: Sends the player to another server
    usage: /sendPlayer <args>
    permission: hungerGamesLobby.admin

  giveMachineGun:
    description: Gives the player a trident that acts like a machine gun
    usage: /giveMachineGun
    permission: hungerGamesLobby.admin

permissions:
  hungerGamesLobby.admin:
    description: allows the player to use administrator commands
